# @package _global_
root_dir: '/workspace/dataset/cassava-leaf-disease-classification'

dataset:
  _target_: dataset.data.DataModule
  train_data_dir: '${root_dir}/train_images'
  val_data_dir: '${root_dir}/train_images'
  df_path: '${root_dir}/train.csv'

  train_dataset_conf:
    img_size: 384
    output_label: True
    one_hot_label: False
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: (${dataset.train_dataset_conf.img_size}, ${dataset.train_dataset_conf.img_size})
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  val_dataset_conf:
    img_size: 384
    output_label: True
    one_hot_label: False
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: (${dataset.val_dataset_conf.img_size}, ${dataset.val_dataset_conf.img_size})
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  train_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4

  val_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4


