# @package _global_
root_dir: '/workspace/dataset/cassava-leaf-disease-classification'

dataset:
  _target_: dataset.data.DataModule
  train_data_dir: '${root_dir}/train_images'
  val_data_dir: '${root_dir}/train_images'
  test_data_dir: '${root_dir}/test_images'
  df_path: '${root_dir}/train.csv'
  submit_df_path: '${root_dir}/sample_submission.csv'

  train_dataset_conf:
    img_size: (288, 384)
    output_label: True
    one_hot_label: True
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: True
    cutmix_params:
      alpha: 1.

  val_dataset_conf:
    img_size: (288, 384)
    output_label: True
    one_hot_label: True
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  test_dataset_conf:
    img_size: (288, 384)
    output_label: False
    one_hot_label: False
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  train_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4

  val_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4
    shuffle: False

  test_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4
    shuffle: False
