# @package _global_
root_dir: '/workspace/dataset/cassava-leaf-disease-classification-merged'

dataset:
  _target_: dataset.data.DataModule
  train_data_dir: '${root_dir}/train'
  val_data_dir: '${root_dir}/train'
  test_data_dir: '/workspace/dataset/cassava-leaf-disease-classification/test_images'
  df_path: '${root_dir}/csv/train_cleanlab_v2.csv' # ['train', 'train_cleanlab_v3', 'train_filterlab_v3]
  submit_df_path: '/workspace/dataset/cassava-leaf-disease-classification/sample_submission.csv'

  train_dataset_conf:
    img_size: (512, 512) # (384, 384) or (512, 512)
    output_label: True
    one_hot_label: True
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: True
    cutmix_params:
      alpha: 1.

  val_dataset_conf:
    img_size: (512, 512)
    output_label: True
    one_hot_label: True
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  test_dataset_conf:
    img_size: (512, 512)
    output_label: False
    one_hot_label: False
    do_fmix: False
    fmix_params:
      alpha: 1.
      decay_power: 3.
      shape: null
      max_soft: True
      reformulate: False
    do_cutmix: False
    cutmix_params:
      alpha: 1.

  train_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4

  val_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4
    shuffle: False

  test_dataloader_conf:
    batch_size: ${batch_size}
    num_workers: 4
    shuffle: False
