seed: 42
device_list: [0]

train:
  n_fold: 5
  n_fold_iter: 5
  n_epochs: 15
  run_test: False

optimizer:
  opt: 'adamp'
  lr: 5e-4
  opt_eps: 1e-8
  # opt_betas: None
  # clip_grad: None
  momentum: 0.9
  weight_decay: 0.05

defaults:
  - dataset: cassava
  - network: efficientnet-b0
  - loss: cross_entropy_onehot

hydra:
  run:
    dir: '/workspace/logs/cassava-leaf-disease-classification/${now:%Y-%m-%d}/${now:%H-%M-%S}'