seed: 42
device_list: [0, 1]
df_path: '${root_dir}/csv/train_filterlab_v3.csv'
log_dir: '/workspace/logs/cassava-leaf-disease-classification'
train:
  n_fold: 5
  use_fold: [0, 1, 2, 3, 4] # [0, 1, 2, 3, 4]
  n_epochs: 10
  total_epoch: 1

  do_load_ckpt: False
  ckpt_params:
    log_path: '${log_dir}/2021-01-29/14-09-48'
    do_freeze_top_layers: True

  do_distillation: True
  distillation_params:
    dir: '${log_dir}/2021-02-03/20-05-04'
    loss:
      name: label_smoothing_onehot
      args:
        smoothing: 0.
        log_softmax: True
    model_name: 'deit_base_patch16_384' # tf_efficientnet_b4_ns
  run_test: True

defaults:
  - dataset: merged_cutmix
  # 'deit_base_distilled_patch16_384' 'deit_base_patch16_384'
  # 'efficientnet-b4' 'resnext50_32x4d' 'resnest50d_1s4x24d'
  - network: deit_base_distilled_patch16_384
  - loss: bi_tempered_logistic_loss
  - optimizer: adamw

hydra:
  run:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: ${hydra.job.num}
