seed: 42
device_list: [1]

train:
  n_fold: 5
  n_fold_iter: 5
  n_epochs: 15
  step_size: 2
  total_epoch: 3
  run_test: False

optimizer:
  opt: 'adamw'
  lr: 5e-4
  opt_eps: 1e-8
  opt_betas: null
  clip_grad: null
  momentum: 0.9
  weight_decay: 1e-5

defaults:
  - dataset: cassava
  - network: efficientnet-b0
  - loss: taylor_cross_entropy_onehot

hydra:
  run:
    dir: '/workspace/logs/cassava-leaf-disease-classification/${now:%Y-%m-%d}/${now:%H-%M-%S}'