seed: 42
device_list: [0, 1]
df_path: '${root_dir}/csv/train_filterlab_v3.csv'
log_dir: '/workspace/logs/cassava-leaf-disease-classification'
train:
  n_fold: 5
  use_fold: [0, 1] # [0, 1, 2, 3, 4]
  n_epochs: 1
  total_epoch: 2

  do_load_ckpt: False
  ckpt_params:
    log_path: '${log_dir}/2021-01-28/09-46-26'
    do_freeze_top_layers: False

  do_distillation: False
  distillation_params:
    dir: '${log_dir}/2021-01-27/19-09-06'
    loss:
      name: label_smoothing_onehot
      args:
        smoothing: 0.2
        log_softmax: True
    model_name: 'vit_base_patch16_384'
  run_test: True

defaults:
  - dataset: merged_cutmix
  # 'deit_base_distilled_patch16_384' 'vit_base_patch16_384'
  # 'efficientnet-b4' 'resnext50_32x4d'
  - network: efficientnet-b0
  - loss: bi_tempered_logistic_loss
  - optimizer: adamw

hydra:
  run:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: ${hydra.job.num}
