seed: 42
device_list: [1]

train:
  n_fold: 5
  n_fold_iter: 1
  n_epochs: 1000
  run_test: True

defaults:
  - dataset: cassava
  - network: efficientnet-b0
  - loss: bi_tempered_logistic_loss

hydra:
  run:
    dir: '/workspace/logs/cassava-leaf-disease-classification/${now:%Y-%m-%d}/${now:%H-%M-%S}'