seed: 42
device_list: [0, 1]
log_dir: '/workspace/logs/cassava-leaf-disease-classification'
train:
  n_fold: 5
  use_fold: [0, 1, 2, 3, 4] # [0, 1, 2, 3, 4]
  n_epochs: 25
  total_epoch: 2
  last_epochs: 0

  do_noise: False
  noise_params:
    alpha: 0.15
    period_epoch: 2
    thr_epochs: 8

  do_load_ckpt: False
  ckpt_params:
    log_path: '${log_dir}/2021-01-28/09-46-26'
    do_freeze_top_layers: False

  do_distillation: True
  distillation_params:
    dir: '${log_dir}/2021-01-28/13-23-00'
    loss:
      name: label_smoothing_onehot
      args:
        smoothing: 0.2
        log_softmax: True
    model_name: 'tf_efficientnet_b4_ns'
  run_test: False

defaults:
  - dataset: merged_cutmix
  - network: deit_base_distilled_patch16_384 # 'deit_base_distilled_patch16_384' 'vit_base_patch16_384' 'efficientnet-b4' 'resnest50d_1s4x24d'
  - loss: bi_tempered_logistic_loss
  - optimizer: adamw

hydra:
  run:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: ${hydra.job.num}
