seed: 42
device_list: [0, 1, 2, 3]
df_path: ${root_dir}/csv/train_label_v4.csv
log_dir: '/workspace/logs/cassava-leaf-disease-classification'
train:
  n_fold: 5
  use_fold: [0, 1, 2, 3, 4] # [0, 1, 2, 3, 4]
  n_epochs: 22
  total_epoch: 2

  do_load_ckpt: False
  finetune: True
  ckpt_params:
    log_path: '${log_dir}/2021-01-25/06-26-25'
    do_freeze_top_layers: True

  do_distillation: False
  distillation_params:
    dir: '${log_dir}/2021-02-07/13-32-06'
    loss:
      name: label_smoothing_onehot
      args:
        smoothing: 0.
        log_softmax: True
    model_name: 'regnety_040' # tf_efficientnet_b4_ns
  run_test: True

defaults:
  - dataset: merged_512_cutmix
  # 'deit_base_distilled_patch16_384' 'deit_base_patch16_384' 'nf_regnet_b4'
  # 'efficientnet-b4' 'resnext50_32x4d' 'resnest50d_1s4x24d' 'regnety_040'
  - network: efficientnet-b4
  # label_smoothing_onehot, bi_tempered_logistic_loss, dmi_loss
  - loss: bi_tempered_logistic_loss
  - optimizer: adam

hydra:
  run:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: ${hydra.job.num}
