seed: 42
device_list: [3]

train:
  n_fold: 5
  n_fold_iter: 5
  n_epochs: 15
  total_epoch: 2
  do_noise: False
  noise_params:
    alpha: 0.2
    period_epoch: 3
    thr_epochs: 8
  run_test: False

optimizer:
  opt: 'adamp'
  lr: 1e-4
  opt_eps: 1e-8
  opt_betas: null
  clip_grad: null
  momentum: 0.9
  weight_decay: 1e-5

defaults:
  - dataset: base
  - network: efficientnet-b0
  - loss: label_smoothing_onehot

hydra:
  run:
    dir: '/workspace/logs/cassava-leaf-disease-classification/${now:%Y-%m-%d}/${now:%H-%M-%S}'
  sweep:
    dir: '/workspace/logs/cassava-leaf-disease-classification/${now:%Y-%m-%d}/${now:%H-%M-%S}'
    subdir: ${hydra.job.num}
