# @package _global_
#batch_size: 16 # (256, 256) 11GB
batch_size: 14
#batch_size: 68  # (512, 512) 11GB finetune

#batch_size: 36  # (512, 512) 24GB
#batch_size:  200 # (512, 512) 24GB finetune


network:
  model_name: 'regnety_040'
  pretrained: True
  num_classes: 5
  in_chans: 3
