# @package _global_
#batch_size: 32 # (288, 384) 11GB
#batch_size: 12 # (512, 512) 11GB
#batch_size: 140 # (512, 512) 11GB fine-tuning

#batch_size: 92 # (288, 384) 24GB
#batch_size: 64 # (384, 384) 24GB
batch_size: 34 # (512, 512) 24GB
#batch_size: 30 # (480, 640) 24GB
#batch_size: 320 # (384, 384) -> (512, 512) 24GB

#batch_size: 60 # (512, 512) 24GB 16 bit

network:
  model_name: 'resnext50_32x4d'
  pretrained: True
  num_classes: 5
  in_chans: 3
