# @package _global_
#batch_size:  # (288, 384) 11GB
batch_size:  15 # (512, 512) 11GB

#batch_size:  # (288, 384) 24GB
#batch_size: 30 # (480, 640) 24GB

network:
  model_name: 'resnest50d_1s4x24d'
  pretrained: True
  num_classes: 5
  in_chans: 3
